### PR TITLE
Bug/36 dont use buffer

### LINKED ISSUE #36: Packaged failed in Vite Application with Buffer Error
- How: Import package in web environment (Vite) 
- Impact: Stopped the frontend from buidling
- Solution -> install Buffer package and set window.Buffer global (hack)
- Request: Remove Buffer in favor of Unit8Array

### PR DESCRIPTION
**Pull request by olehnikolaiev**
fixes #36 

- use Uint8Array in favour of Buffer
- update skaled and sgxwallet versions used for tests, update default config
- bump package version

### CODE REVIEW

File: src/utils/bytes.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ * along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ */
+
+/**
+ * @file bytes.ts
+ * @copyright SKALE Labs 2026-Present
+ */
+
+export function hexToBytes(hex: string): Uint8Array {
+    const sanitizedHex = hex.startsWith('0x') ? hex.slice(2) : hex;
```
Comment (DmytroNazarenko) [inline src/utils/bytes.ts:27]: Let's use validateHexString here

**Review by DmytroNazarenko — APPROVED** [review]
